version: 0.2

phases:
  build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v9u5b3u6
      - ./gradlew build
      - docker build --build-arg DEPENDENCY=build/dependency -t springboot-gradle-docker-aws .
      - docker tag springboot-gradle-docker-aws:latest public.ecr.aws/v9u5b3u6/springboot-gradle-docker-aws:latest
      - docker push public.ecr.aws/v9u5b3u6/springboot-gradle-docker-aws:latest
